apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  SAMPLE_KEY: sample_value
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: app
type: Opaque
data:
  SECRET_KEY: c2VjcmV0 # 'secret' in base64
